version: "3.9"
services:

  postgres:
    image: "postgres:14"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=example
      - POSTGRES_DB=example_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 2s
      retries: 5

  psql2py:
    image: "psql2py"
    volumes:
      - ./sql:/input:ro
      - .:/output:rw
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=password
      - DB_USER=example
      - DB_NAME=example_db
    depends_on:
      postgres:
        condition: service_healthy