from typing import Protocol


class PythonType(Protocol):
    def type_hint(self) -> str: ...
    def imports(self) -> list[str]: ...


class NamedPythonType(Protocol):
    def type_hint(self) -> str: ...
    def imports(self) -> list[str]: ...
    def name(self) -> str: ...

